- block:
  - set_fact:
      homebrew_repo: "{{ homebrew_repo_darwin }}"
    when: ansible_os_family == "Darwin"

  - set_fact:
      homebrew_repo: "{{ homebrew_repo_linux }}"
    when: ansible_os_family != "Darwin"
  when: homebrew_repo is not defined

- block:
  - set_fact:
      homebrew_install_path: "{{ homebrew_install_path_darwin }}"
    when: ansible_os_family == "Darwin"

  - set_fact:
      homebrew_install_path: "{{ ansible_env.HOME }}/.linuxbrew"
    when: ansible_os_family != "Darwin"
  when: homebrew_install_path is not defined

- block:
  - set_fact:
      homebrew_prefix: "{{ homebrew_prefix_darwin }}"
    when: ansible_os_family == "Darwin"

  - set_fact:
      homebrew_prefix: "{{ homebrew_install_path }}"
    when: ansible_os_family != "Darwin"
  when: homebrew_prefix is not defined

- block:
  - set_fact:
      homebrew_brew_bin_path: "{{ homebrew_brew_bin_path_darwin }}"
    when: ansible_os_family == "Darwin"

  - set_fact:
      homebrew_brew_bin_path: "{{ homebrew_install_path }}/bin"
    when: ansible_os_family != "Darwin"
  when: homebrew_brew_bin_path is not defined

