---
dependency:
  name: galaxy
  options:
    role-file: tests/requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ${MOLECULE_NAME}
    box: ${MOLECULE_BOX}
    box_version: ${MOLECULE_BOX_VERSION}
    memory: 2048
    cpus: 4
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: ../../tests/test.yml
    destroy: destroy.yml
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  directory: ../../tests/
  options:
    verbose: true
  lint:
    name: flake8
